<!--#include virtual="/x-objects-new/content/restricted.inc"-->
<!--#include virtual="/x-objects-new/content/all.inc"-->
<html>
<head>
<title>Seagate Software: TITLE GOES HERE</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta name="SUMMARY" content="$Header: /community/_sharedtemplates/pages/templates/typestyles.asp 2     5/17/99 7:19p Eglass $">
<meta name="LOCATION" content="$Archive: /community/_sharedtemplates/pages/templates/typestyles.asp $">
<meta name="REVISION" content="$Revision: 2 $">
<meta name="MODIFIED" content="$Date: 5/17/99 7:19p $">
<meta name="AUTHOR" content="$Author: Eglass $">
<meta name="PUBLISHER" content="Seagate Software">
<link rel="stylesheet" href="main.css" type="text/css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" marginspacing="0" bgcolor="#FFFFFF" text="#000000" link="#0000FF" vlink="#800080" alink="#FF0000">
<table border="0" cellpadding="0" cellspacing="0" width="760">
  <tr align="left" valign="top"> 
    <td align="left" valign="top" width="130" height="1" bgcolor="#000000" class="xMASTHEADLOGO"><img src="shim.gif" width="130" height="1" border="0"></td>
    <td align="left" valign="top" width="10" height="1" bgcolor="#000000" class="xMASTHEADLOGO"><img src="shim.gif" width="10" height="1" border="0"></td>
    <td align="left" valign="top" width="400" height="1" bgcolor="#000000" class="xMASTHEADLOGO"><img src="shim.gif" width="400" height="1" border="0"></td>
    <td align="left" valign="top" width="60" height="1" bgcolor="#000000" class="xMASTHEADLOGO"><img src="shim.gif" width="60" height="1" border="0"></td>
    <td align="left" valign="top" width="10" height="1" bgcolor="#000000" class="xMASTHEADLOGO"><img src="shim.gif" width="10" height="1" border="0"></td>
    <td align="left" valign="top" width="150" height="1" bgcolor="#000000" class="xMASTHEADLOGO"><img src="shim.gif" width="150" height="1" border="0"></td>
  </tr>
  <tr align="left" valign="top"> 
    <td align="left" valign="middle" height="47" colspan="3" bgcolor="#000000" class="xMASTHEADLOGO"><a href="/homepage/"><img src="logo_seagate_black_large.gif" alt="Seagate Software" border="0" width="162" height="30"></a></td>
    <td align="left" valign="top" colspan="3" rowspan="3"><%=DisplayDog%></td>
  </tr>
  <tr align="left" valign="top"> 
    <td align="left" valign="middle" height="29" colspan="3" bgcolor="#6699CC" class="xMASTHEADLIGHT"><%=DisplayMastheadTagline (true)%></td>
  </tr>
  <tr align="left" valign="top"> 
    <td align="left" valign="top" bgcolor="#6699CC" class="xMASTHEADLIGHT">&nbsp;</td>
    <td align="left" valign="top"><img src="images/nub_topleft_navtomasthead.gif" width="10" height="10"></td>
    <td align="left" valign="top"><%=DisplayTopNav%></td>
  </tr>
  <tr align="left" valign="top"> 
    <td align="left" valign="top"><%=Menu%></td>
    <td align="left" valign="top" rowspan="3"></td>
    <td align="left" valign="top" colspan="2" rowspan="2">HEADLINE
      <p class="ssiHEADLINES">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>SUBHEADINGS</p>
      <p class="ssiSUBHEADINGS">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>INSTRUCTIONS</p>
      <p class="ssiINSTRUCTIONS">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>BODY COPY</p>
      <p class="ssiBODYCOPY">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>PLACEHOLDER COPY</p>
      <p class="ssiPLACEHOLDER">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>DEVICES</p>
      <p class="ssiDEVICES">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>FORM FIELD</p>
      <p class="xFORMFIELD">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>FORM INSTRUCTIONS</p>
      <p class="xFORMINSTRUCTIONS">THIS IS THE MAIN STAGE. It is cool.</p>
      <p>REQUIRED FIELD INDICATOR</p>
      <p class="xREQUIREDFIELD">*</p>
      <p>&nbsp;</p>
    </td>
    <td align="left" valign="top" rowspan="3"></td>
    <td align="left" valign="top" rowspan="2">
    		<!--webbot bot="PurpleText" PREVIEW="delete this; edit for sidebars" -->
    </td>
  </tr>
  <tr align="left" valign="top"> 
    <td align="left" valign="top">
    		<!--webbot bot="PurpleText" PREVIEW="delete this; edit for callouts" -->
    </td>
  </tr>
  <tr align="left" valign="top"> 
    <td align="left" valign="top">
			<!-- do not edit -->
    </td>
    <td align="left" valign="top" colspan="2">
			<%=DisplayFooter%>
	    	<%=DisplayCopyright%>
    </td>
    <td align="left" valign="top">
    <!-- do not edit -->
    </td>
  </tr>
</table>
<!--webbot bot="PurpleText" PREVIEW="Only edit the marked areas in the table above. Do not edit outside the table." -->
</body>
</html>
